/**
 * FluereScrollView 命名常量。
 *
 * 集中收拢有领域含义的字面量（对齐 oxlint no-magic-numbers），
 * 让 ScrollView 各拆分模块共享同一份数值契约，避免魔数散落。
 */

const MIN_OFFSET = 0
const THUMB_MIN_LENGTH = 30
const MIN_THUMB_TRAVEL = 1
const BARS_HIDE_DELAY = 2000
const BARS_HOVER_DELAY = 400
const SCROLL_ANIMATION_DURATION = 400
const DEFAULT_INERTIA_DECAY = 0.95
const WHEEL_LINE_HEIGHT = 16
const WHEEL_ZOOM_FACTOR_STEP = 1.2
const WHEEL_ZOOM_STEP_DIVISOR = 100
const RAIL_THRESHOLD = 10
const INERTIA_SPEED_THRESHOLD = 200
const VELOCITY_SMOOTHING_ALPHA = 0.8
const VELOCITY_SMOOTHING_BETA = 0.2
const KEYBOARD_STEP_MIN = 40
const KEYBOARD_STEP_RATIO = 0.1
const PAGE_SCROLL_MARGIN = 40
const MIN_POINTER_DELTA_TIME = 1
const MAX_FRAME_DELTA_TIME = 0.064
const VELOCITY_EPSILON = 0.5
const OFFSET_VELOCITY_EPSILON = 0.01
const ZOOM_VELOCITY_STOP = 0.001
const ZOOM_VELOCITY_BOUNDARY = 0.01
const ZOOM_VELOCITY_EPSILON = 0.0001
const NEWTON_MAX_ITERATIONS = 8
const NEWTON_TOLERANCE = 1e-5
const NEWTON_DERIVATIVE_TOLERANCE = 1e-6
const DECELERATE_P0_X = 0.1
const DECELERATE_P0_Y = 0.9
const DECELERATE_P1_X = 0.2
const DECELERATE_P1_Y = 1
const MS_PER_SECOND = 1000
const PRIMARY_BUTTON = 0
const INITIAL_ZOOM_FACTOR = 1
const HALF = 0.5

export {
  BARS_HIDE_DELAY,
  BARS_HOVER_DELAY,
  DECELERATE_P0_X,
  DECELERATE_P0_Y,
  DECELERATE_P1_X,
  DECELERATE_P1_Y,
  DEFAULT_INERTIA_DECAY,
  HALF,
  INITIAL_ZOOM_FACTOR,
  INERTIA_SPEED_THRESHOLD,
  KEYBOARD_STEP_MIN,
  KEYBOARD_STEP_RATIO,
  MAX_FRAME_DELTA_TIME,
  MIN_OFFSET,
  MIN_POINTER_DELTA_TIME,
  MIN_THUMB_TRAVEL,
  MS_PER_SECOND,
  NEWTON_DERIVATIVE_TOLERANCE,
  NEWTON_MAX_ITERATIONS,
  NEWTON_TOLERANCE,
  OFFSET_VELOCITY_EPSILON,
  PAGE_SCROLL_MARGIN,
  PRIMARY_BUTTON,
  RAIL_THRESHOLD,
  SCROLL_ANIMATION_DURATION,
  THUMB_MIN_LENGTH,
  VELOCITY_EPSILON,
  VELOCITY_SMOOTHING_ALPHA,
  VELOCITY_SMOOTHING_BETA,
  WHEEL_LINE_HEIGHT,
  WHEEL_ZOOM_FACTOR_STEP,
  WHEEL_ZOOM_STEP_DIVISOR,
  ZOOM_VELOCITY_BOUNDARY,
  ZOOM_VELOCITY_EPSILON,
  ZOOM_VELOCITY_STOP,
}
