/* oxlint-disable import/no-nodejs-modules, no-magic-numbers, prefer-named-capture-group, no-null, no-continue, no-ternary, capitalized-comments, id-length, curly, max-statements, func-style, no-array-sort, max-nested-calls -- 一次性图标生成工具脚本，Node 内建模块为有意使用 */
/**
 * 从官方 `@fluentui/svg-icons`（MIT，微软 Fluent System Icons 优化 SVG 包）生成 Vue 图标组件库：
 *   - generated/<size>-<style>.ts   每个「尺寸 × 风格」一个模块，导出该组合下的全部图标组件（tree-shakeable）
 *   - generated/index.ts            聚合导出（`export *`）
 *   - generated/names.ts            图标名联合类型与常量数组
 *   - generated/icons.json          元数据注册表（docs 图标浏览器用，不含 path 数据）
 *
 * 用法：node scripts/sync-icons.mjs
 * 重建：pnpm --filter @fluere-vue/icons sync
 *
 * 源包解析顺序：
 *   1. 环境变量 FLUENT_SVG_ICONS_DIR（指向含 *_regular.svg 的目录）
 *   2. 本包依赖的 @fluentui/svg-icons 的 icons/ 目录
 *   3. pnpm store（.pnpm 下 @fluentui+svg-icons 的 node_modules/@fluentui/svg-icons/icons）兜底
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const require = createRequire(import.meta.url)
const outDir = join(here, '..', 'generated')
mkdirSync(outDir, { recursive: true })

/* ------------------------------------------------------------------ */
/* 1) 定位源目录                                                       */
/* ------------------------------------------------------------------ */
function findSourceDir() {
  const fromEnv = process.env.FLUENT_SVG_ICONS_DIR
  if (fromEnv) return fromEnv

  const tryResolve = (specifier) => {
    try {
      const pkgJson = require.resolve(specifier)
      return join(dirname(pkgJson), 'icons')
    } catch {
      return null
    }
  }
  const resolved = tryResolve('@fluentui/svg-icons/package.json')
  if (resolved) return resolved

  // pnpm store 兜底（本包尚未安装依赖时的降级路径）
  const storeRoot = join(here, '..', '..', '..', 'node_modules', '.pnpm')
  try {
    const candidates = readdirSync(storeRoot).filter((name) =>
      name.startsWith('@fluentui+svg-icons@'),
    )
    if (candidates.length > 0) {
      return join(storeRoot, candidates[0], 'node_modules', '@fluentui', 'svg-icons', 'icons')
    }
  } catch {
    /* store 不存在则继续走报错 */
  }
  throw new Error(
    '找不到 @fluentui/svg-icons 源包。请先 `pnpm install`，或通过 FLUENT_SVG_ICONS_DIR 指向含 *_regular.svg 的目录。',
  )
}

const sourceDir = findSourceDir()
let sourceVersion = 'unknown'
try {
  const pkgJson = JSON.parse(readFileSync(join(dirname(sourceDir), 'package.json'), 'utf8'))
  sourceVersion = pkgJson.version
} catch {
  /* 版本仅用于头注释，缺省不影响生成 */
}

/* ------------------------------------------------------------------ */
/* 2) 解析 SVG：抽取 path d 数据（跳过 defs/clipPath 内的矩形）          */
/* ------------------------------------------------------------------ */
const PATH_RE = /<path\b[^>]*\bd="([^"]*)"[^>]*>/g
const STYLE_RE = /^(.*)_(\d+)_(regular|filled)\.svg$/

const parsePaths = (svg) => {
  const withoutDefs = svg.replace(/<defs>[\s\S]*?<\/defs>/g, '')
  const paths = []
  for (const match of withoutDefs.matchAll(PATH_RE)) paths.push(match[1])
  return paths
}

/* ------------------------------------------------------------------ */
/* 3) 收集图标                                                          */
/* ------------------------------------------------------------------ */
const iconMap = new Map() // key: `${size}-${style}` -> Map<name, paths[]>
const byName = new Map() // name -> Set<`${size}:${style}`>

const files = readdirSync(sourceDir, { withFileTypes: true })
for (const entry of files) {
  if (!entry.isFile()) continue // 跳过 LTR/RTL/ar 等子目录
  const match = entry.name.match(STYLE_RE)
  if (!match) continue // 跳过 _color / _light 及其它
  const [, name, sizeStr, style] = match
  const size = Number(sizeStr)
  const svg = readFileSync(join(sourceDir, entry.name), 'utf8')
  const paths = parsePaths(svg)
  if (paths.length === 0) {
    console.warn(`[warn] ${entry.name} 未解析到 path，已跳过`)
    continue
  }
  const key = `${size}-${style}`
  if (!iconMap.has(key)) iconMap.set(key, new Map())
  iconMap.get(key).set(name, paths)
  if (!byName.has(name)) byName.set(name, new Set())
  byName.get(name).add(`${size}:${style}`)
}

const sizes = [...new Set([...iconMap.keys()].map((key) => Number(key.split('-')[0])))].sort(
  (a, b) => a - b,
)
const styles = ['regular', 'filled']
const names = [...byName.keys()].sort()
const STYLE_ORDER = { regular: 0, filled: 1 }

const header = (lines) =>
  [
    '/* @generated by scripts/sync-icons.mjs from @fluentui/svg-icons' +
      `@${sourceVersion} — do not edit by hand. */`,
    '/* Rebuild: pnpm --filter @fluere-vue/icons sync */',
    '',
    ...lines,
    '',
  ].join('\n')

/* ------------------------------------------------------------------ */
/* 4) 组件模块：generated/<size>-<style>.ts                            */
/* ------------------------------------------------------------------ */
const pascalCase = (name) =>
  name
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')

for (const size of sizes) {
  for (const style of styles) {
    const key = `${size}-${style}`
    const icons = iconMap.get(key)
    if (!icons) continue
    const namesInGroup = [...icons.keys()].sort()
    const body = namesInGroup.map((name) => {
      const exportName = `FluentIcon${pascalCase(name)}${size}${style === 'regular' ? 'Regular' : 'Filled'}`
      const paths = icons
        .get(name)
        .map((d) => `'${d}'`)
        .join(', ')
      return `export const ${exportName} = /* @__PURE__ */ createFluentIcon({ name: '${name}', size: ${size}, style: '${style}', paths: [${paths}] })`
    })
    writeFileSync(
      join(outDir, `${key}.ts`),
      header(["import { createFluentIcon } from '../src/factory'", '', ...body]),
    )
  }
}

/* ------------------------------------------------------------------ */
/* 5) generated/index.ts                                              */
/* ------------------------------------------------------------------ */
const indexBody = []
for (const size of sizes) {
  for (const style of styles) {
    const key = `${size}-${style}`
    if (iconMap.has(key)) indexBody.push(`export * from './${key}'`)
  }
}
writeFileSync(join(outDir, 'index.ts'), header(indexBody))

/* ------------------------------------------------------------------ */
/* 6) generated/names.ts                                              */
/* ------------------------------------------------------------------ */
const sizeUnion = sizes.join(' | ')
const nameUnion = names.map((name) => `'${name}'`).join(' | ')
const nameList = names.map((name) => `  '${name}',`).join('\n')
writeFileSync(
  join(outDir, 'names.ts'),
  header([
    `export type FluentIconSize = ${sizeUnion}`,
    '',
    `export type FluentIconStyle = 'regular' | 'filled'`,
    '',
    `export type FluentIconName = ${nameUnion}`,
    '',
    'export const fluentIconNames = [',
    nameList,
    '] as const satisfies readonly FluentIconName[]',
  ]),
)

/* ------------------------------------------------------------------ */
/* 7) generated/icons.json                                            */
/* ------------------------------------------------------------------ */
const iconEntries = names.map((name) => {
  const combos = [...byName.get(name)].sort()
  const sizeMap = {}
  for (const combo of combos) {
    const [size, style] = combo.split(':')
    sizeMap[size] ??= []
    sizeMap[size].push(style)
  }
  for (const list of Object.values(sizeMap)) {
    list.sort((a, b) => STYLE_ORDER[a] - STYLE_ORDER[b])
  }
  return { name, sizes: sizeMap }
})
writeFileSync(
  join(outDir, 'icons.json'),
  `${JSON.stringify(
    {
      source: '@fluentui/svg-icons',
      sourceVersion,
      totalNames: names.length,
      totalIcons: files.filter((f) => f.isFile() && STYLE_RE.test(f.name)).length,
      sizes,
      icons: iconEntries,
    },
    null,
    2,
  )}\n`,
)

console.log(
  `[ok] ${names.length} 个图标名 / ${styles.length} 种风格 × ${sizes.length} 种尺寸，生成至 ${outDir}`,
)
