// Fluent 2 design tokens for Flutter, generated from @fluentui/tokens.
// Semantic color constants keep the exact @fluentui/tokens camelCase names.
import 'dart:ui';
import 'dart:ui' show FontWeight;

/// Fluent 2 semantic colors — the light theme (default web brand).
/// Values come straight from @fluentui/tokens alias.lightWeb.
abstract class FluentLightColors {
  static const Color colorNeutralForeground1 = const Color(0xFF242424); // #242424
  static const Color colorNeutralForeground1Hover = const Color(0xFF242424); // #242424
  static const Color colorNeutralForeground1Pressed = const Color(0xFF242424); // #242424
  static const Color colorNeutralForeground1Selected = const Color(0xFF242424); // #242424
  static const Color colorNeutralForeground2 = const Color(0xFF424242); // #424242
  static const Color colorNeutralForeground2Hover = const Color(0xFF242424); // #242424
  static const Color colorNeutralForeground2Pressed = const Color(0xFF242424); // #242424
  static const Color colorNeutralForeground2Selected = const Color(0xFF242424); // #242424
  static const Color colorNeutralForeground2BrandHover = const Color(0xFF0F6CBD); // #0f6cbd
  static const Color colorNeutralForeground2BrandPressed = const Color(0xFF115EA3); // #115ea3
  static const Color colorNeutralForeground2BrandSelected = const Color(0xFF0F6CBD); // #0f6cbd
  static const Color colorNeutralForeground3 = const Color(0xFF616161); // #616161
  static const Color colorNeutralForeground3Hover = const Color(0xFF424242); // #424242
  static const Color colorNeutralForeground3Pressed = const Color(0xFF424242); // #424242
  static const Color colorNeutralForeground3Selected = const Color(0xFF424242); // #424242
  static const Color colorNeutralForeground3BrandHover = const Color(0xFF0F6CBD); // #0f6cbd
  static const Color colorNeutralForeground3BrandPressed = const Color(0xFF115EA3); // #115ea3
  static const Color colorNeutralForeground3BrandSelected = const Color(0xFF0F6CBD); // #0f6cbd
  static const Color colorNeutralForeground4 = const Color(0xFF707070); // #707070
  static const Color colorNeutralForeground5 = const Color(0xFF616161); // #616161
  static const Color colorNeutralForeground5Hover = const Color(0xFF242424); // #242424
  static const Color colorNeutralForeground5Pressed = const Color(0xFF242424); // #242424
  static const Color colorNeutralForeground5Selected = const Color(0xFF242424); // #242424
  static const Color colorNeutralForegroundDisabled = const Color(0xFFBDBDBD); // #bdbdbd
  static const Color colorNeutralForegroundInvertedDisabled = const Color(0x66FFFFFF); // rgba(255, 255, 255, 0.4)
  static const Color colorBrandForegroundLink = const Color(0xFF115EA3); // #115ea3
  static const Color colorBrandForegroundLinkHover = const Color(0xFF0F548C); // #0f548c
  static const Color colorBrandForegroundLinkPressed = const Color(0xFF0C3B5E); // #0c3b5e
  static const Color colorBrandForegroundLinkSelected = const Color(0xFF115EA3); // #115ea3
  static const Color colorNeutralForeground2Link = const Color(0xFF424242); // #424242
  static const Color colorNeutralForeground2LinkHover = const Color(0xFF242424); // #242424
  static const Color colorNeutralForeground2LinkPressed = const Color(0xFF242424); // #242424
  static const Color colorNeutralForeground2LinkSelected = const Color(0xFF242424); // #242424
  static const Color colorCompoundBrandForeground1 = const Color(0xFF0F6CBD); // #0f6cbd
  static const Color colorCompoundBrandForeground1Hover = const Color(0xFF115EA3); // #115ea3
  static const Color colorCompoundBrandForeground1Pressed = const Color(0xFF0F548C); // #0f548c
  static const Color colorBrandForeground1 = const Color(0xFF0F6CBD); // #0f6cbd
  static const Color colorBrandForeground2 = const Color(0xFF115EA3); // #115ea3
  static const Color colorBrandForeground2Hover = const Color(0xFF0F548C); // #0f548c
  static const Color colorBrandForeground2Pressed = const Color(0xFF0A2E4A); // #0a2e4a
  static const Color colorNeutralForeground1Static = const Color(0xFF242424); // #242424
  static const Color colorNeutralForegroundStaticInverted = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForegroundInverted = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForegroundInvertedHover = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForegroundInvertedPressed = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForegroundInvertedSelected = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForegroundInverted2 = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForegroundOnBrand = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForegroundInvertedLink = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForegroundInvertedLinkHover = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForegroundInvertedLinkPressed = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForegroundInvertedLinkSelected = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorBrandForegroundInverted = const Color(0xFF479EF5); // #479ef5
  static const Color colorBrandForegroundInvertedHover = const Color(0xFF62ABF5); // #62abf5
  static const Color colorBrandForegroundInvertedPressed = const Color(0xFF479EF5); // #479ef5
  static const Color colorBrandForegroundOnLight = const Color(0xFF0F6CBD); // #0f6cbd
  static const Color colorBrandForegroundOnLightHover = const Color(0xFF115EA3); // #115ea3
  static const Color colorBrandForegroundOnLightPressed = const Color(0xFF0E4775); // #0e4775
  static const Color colorBrandForegroundOnLightSelected = const Color(0xFF0F548C); // #0f548c
  static const Color colorNeutralBackground1 = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralBackground1Hover = const Color(0xFFF5F5F5); // #f5f5f5
  static const Color colorNeutralBackground1Pressed = const Color(0xFFE0E0E0); // #e0e0e0
  static const Color colorNeutralBackground1Selected = const Color(0xFFEBEBEB); // #ebebeb
  static const Color colorNeutralBackground2 = const Color(0xFFFAFAFA); // #fafafa
  static const Color colorNeutralBackground2Hover = const Color(0xFFF0F0F0); // #f0f0f0
  static const Color colorNeutralBackground2Pressed = const Color(0xFFDBDBDB); // #dbdbdb
  static const Color colorNeutralBackground2Selected = const Color(0xFFE6E6E6); // #e6e6e6
  static const Color colorNeutralBackground3 = const Color(0xFFF5F5F5); // #f5f5f5
  static const Color colorNeutralBackground3Hover = const Color(0xFFEBEBEB); // #ebebeb
  static const Color colorNeutralBackground3Pressed = const Color(0xFFD6D6D6); // #d6d6d6
  static const Color colorNeutralBackground3Selected = const Color(0xFFE0E0E0); // #e0e0e0
  static const Color colorNeutralBackground4 = const Color(0xFFF0F0F0); // #f0f0f0
  static const Color colorNeutralBackground4Hover = const Color(0xFFFAFAFA); // #fafafa
  static const Color colorNeutralBackground4Pressed = const Color(0xFFF5F5F5); // #f5f5f5
  static const Color colorNeutralBackground4Selected = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralBackground5 = const Color(0xFFEBEBEB); // #ebebeb
  static const Color colorNeutralBackground5Hover = const Color(0xFFF5F5F5); // #f5f5f5
  static const Color colorNeutralBackground5Pressed = const Color(0xFFF0F0F0); // #f0f0f0
  static const Color colorNeutralBackground5Selected = const Color(0xFFFAFAFA); // #fafafa
  static const Color colorNeutralBackground6 = const Color(0xFFE6E6E6); // #e6e6e6
  static const Color colorNeutralBackground7 = const Color(0x00000000); // #00000000
  static const Color colorNeutralBackground7Hover = const Color(0xFFEBEBEB); // #ebebeb
  static const Color colorNeutralBackground7Pressed = const Color(0xFFD6D6D6); // #d6d6d6
  static const Color colorNeutralBackground7Selected = const Color(0x00000000); // #00000000
  static const Color colorNeutralBackground8 = const Color(0xFFFCFCFC); // #fcfcfc
  static const Color colorNeutralBackgroundInverted = const Color(0xFF292929); // #292929
  static const Color colorNeutralBackgroundInvertedHover = const Color(0xFF3D3D3D); // #3d3d3d
  static const Color colorNeutralBackgroundInvertedPressed = const Color(0xFF1F1F1F); // #1f1f1f
  static const Color colorNeutralBackgroundInvertedSelected = const Color(0xFF383838); // #383838
  static const Color colorNeutralBackgroundStatic = const Color(0xFF333333); // #333333
  static const Color colorNeutralBackgroundAlpha = const Color(0x80FFFFFF); // rgba(255, 255, 255, 0.5)
  static const Color colorNeutralBackgroundAlpha2 = const Color(0xCCFFFFFF); // rgba(255, 255, 255, 0.8)
  static const Color colorSubtleBackground = const Color(0x00000000); // transparent
  static const Color colorSubtleBackgroundHover = const Color(0xFFF5F5F5); // #f5f5f5
  static const Color colorSubtleBackgroundPressed = const Color(0xFFE0E0E0); // #e0e0e0
  static const Color colorSubtleBackgroundSelected = const Color(0xFFEBEBEB); // #ebebeb
  static const Color colorSubtleBackgroundLightAlphaHover = const Color(0xB3FFFFFF); // rgba(255, 255, 255, 0.7)
  static const Color colorSubtleBackgroundLightAlphaPressed = const Color(0x80FFFFFF); // rgba(255, 255, 255, 0.5)
  static const Color colorSubtleBackgroundLightAlphaSelected = const Color(0x00000000); // transparent
  static const Color colorSubtleBackgroundInverted = const Color(0x00000000); // transparent
  static const Color colorSubtleBackgroundInvertedHover = const Color(0x1A000000); // rgba(0, 0, 0, 0.1)
  static const Color colorSubtleBackgroundInvertedPressed = const Color(0x4D000000); // rgba(0, 0, 0, 0.3)
  static const Color colorSubtleBackgroundInvertedSelected = const Color(0x33000000); // rgba(0, 0, 0, 0.2)
  static const Color colorTransparentBackground = const Color(0x00000000); // transparent
  static const Color colorTransparentBackgroundHover = const Color(0x00000000); // transparent
  static const Color colorTransparentBackgroundPressed = const Color(0x00000000); // transparent
  static const Color colorTransparentBackgroundSelected = const Color(0x00000000); // transparent
  static const Color colorNeutralBackgroundDisabled = const Color(0xFFF0F0F0); // #f0f0f0
  static const Color colorNeutralBackgroundDisabled2 = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralBackgroundInvertedDisabled = const Color(0x1AFFFFFF); // rgba(255, 255, 255, 0.1)
  static const Color colorNeutralStencil1 = const Color(0xFFE6E6E6); // #e6e6e6
  static const Color colorNeutralStencil2 = const Color(0xFFFAFAFA); // #fafafa
  static const Color colorNeutralStencil1Alpha = const Color(0x1A000000); // rgba(0, 0, 0, 0.1)
  static const Color colorNeutralStencil2Alpha = const Color(0xD000000); // rgba(0, 0, 0, 0.05)
  static const Color colorBackgroundOverlay = const Color(0x66000000); // rgba(0, 0, 0, 0.4)
  static const Color colorScrollbarOverlay = const Color(0x80000000); // rgba(0, 0, 0, 0.5)
  static const Color colorBrandBackground = const Color(0xFF0F6CBD); // #0f6cbd
  static const Color colorBrandBackgroundHover = const Color(0xFF115EA3); // #115ea3
  static const Color colorBrandBackgroundPressed = const Color(0xFF0C3B5E); // #0c3b5e
  static const Color colorBrandBackgroundSelected = const Color(0xFF0F548C); // #0f548c
  static const Color colorCompoundBrandBackground = const Color(0xFF0F6CBD); // #0f6cbd
  static const Color colorCompoundBrandBackgroundHover = const Color(0xFF115EA3); // #115ea3
  static const Color colorCompoundBrandBackgroundPressed = const Color(0xFF0F548C); // #0f548c
  static const Color colorBrandBackgroundStatic = const Color(0xFF0F6CBD); // #0f6cbd
  static const Color colorBrandBackground2 = const Color(0xFFEBF3FC); // #ebf3fc
  static const Color colorBrandBackground2Hover = const Color(0xFFCFE4FA); // #cfe4fa
  static const Color colorBrandBackground2Pressed = const Color(0xFF96C6FA); // #96c6fa
  static const Color colorBrandBackground3Static = const Color(0xFF0F548C); // #0f548c
  static const Color colorBrandBackground4Static = const Color(0xFF0C3B5E); // #0c3b5e
  static const Color colorBrandBackgroundInverted = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorBrandBackgroundInvertedHover = const Color(0xFFEBF3FC); // #ebf3fc
  static const Color colorBrandBackgroundInvertedPressed = const Color(0xFFB4D6FA); // #b4d6fa
  static const Color colorBrandBackgroundInvertedSelected = const Color(0xFFCFE4FA); // #cfe4fa
  static const Color colorNeutralCardBackground = const Color(0xFFFAFAFA); // #fafafa
  static const Color colorNeutralCardBackgroundHover = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralCardBackgroundPressed = const Color(0xFFF5F5F5); // #f5f5f5
  static const Color colorNeutralCardBackgroundSelected = const Color(0xFFEBEBEB); // #ebebeb
  static const Color colorNeutralCardBackgroundDisabled = const Color(0xFFF0F0F0); // #f0f0f0
  static const Color colorNeutralStrokeAccessible = const Color(0xFF616161); // #616161
  static const Color colorNeutralStrokeAccessibleHover = const Color(0xFF575757); // #575757
  static const Color colorNeutralStrokeAccessiblePressed = const Color(0xFF4D4D4D); // #4d4d4d
  static const Color colorNeutralStrokeAccessibleSelected = const Color(0xFF0F6CBD); // #0f6cbd
  static const Color colorNeutralStroke1 = const Color(0xFFD1D1D1); // #d1d1d1
  static const Color colorNeutralStroke1Hover = const Color(0xFFC7C7C7); // #c7c7c7
  static const Color colorNeutralStroke1Pressed = const Color(0xFFB3B3B3); // #b3b3b3
  static const Color colorNeutralStroke1Selected = const Color(0xFFBDBDBD); // #bdbdbd
  static const Color colorNeutralStroke2 = const Color(0xFFE0E0E0); // #e0e0e0
  static const Color colorNeutralStroke3 = const Color(0xFFF0F0F0); // #f0f0f0
  static const Color colorNeutralStroke4 = const Color(0xFFEBEBEB); // #ebebeb
  static const Color colorNeutralStroke4Hover = const Color(0xFFE0E0E0); // #e0e0e0
  static const Color colorNeutralStroke4Pressed = const Color(0xFFD6D6D6); // #d6d6d6
  static const Color colorNeutralStroke4Selected = const Color(0xFFEBEBEB); // #ebebeb
  static const Color colorNeutralStrokeSubtle = const Color(0xFFE0E0E0); // #e0e0e0
  static const Color colorNeutralStrokeOnBrand = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralStrokeOnBrand2 = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralStrokeOnBrand2Hover = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralStrokeOnBrand2Pressed = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralStrokeOnBrand2Selected = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorBrandStroke1 = const Color(0xFF0F6CBD); // #0f6cbd
  static const Color colorBrandStroke2 = const Color(0xFFB4D6FA); // #b4d6fa
  static const Color colorBrandStroke2Hover = const Color(0xFF77B7F7); // #77b7f7
  static const Color colorBrandStroke2Pressed = const Color(0xFF0F6CBD); // #0f6cbd
  static const Color colorBrandStroke2Contrast = const Color(0xFFB4D6FA); // #b4d6fa
  static const Color colorCompoundBrandStroke = const Color(0xFF0F6CBD); // #0f6cbd
  static const Color colorCompoundBrandStrokeHover = const Color(0xFF115EA3); // #115ea3
  static const Color colorCompoundBrandStrokePressed = const Color(0xFF0F548C); // #0f548c
  static const Color colorNeutralStrokeDisabled = const Color(0xFFE0E0E0); // #e0e0e0
  static const Color colorNeutralStrokeDisabled2 = const Color(0xFFEBEBEB); // #ebebeb
  static const Color colorNeutralStrokeInvertedDisabled = const Color(0x66FFFFFF); // rgba(255, 255, 255, 0.4)
  static const Color colorTransparentStroke = const Color(0x00000000); // transparent
  static const Color colorTransparentStrokeInteractive = const Color(0x00000000); // transparent
  static const Color colorTransparentStrokeDisabled = const Color(0x00000000); // transparent
  static const Color colorNeutralStrokeAlpha = const Color(0xD000000); // rgba(0, 0, 0, 0.05)
  static const Color colorNeutralStrokeAlpha2 = const Color(0x33FFFFFF); // rgba(255, 255, 255, 0.2)
  static const Color colorStrokeFocus1 = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorStrokeFocus2 = const Color(0xFF000000); // #000000
  static const Color colorNeutralShadowAmbient = const Color(0x1F000000); // rgba(0,0,0,0.12)
  static const Color colorNeutralShadowKey = const Color(0x24000000); // rgba(0,0,0,0.14)
  static const Color colorNeutralShadowAmbientLighter = const Color(0xF000000); // rgba(0,0,0,0.06)
  static const Color colorNeutralShadowKeyLighter = const Color(0x12000000); // rgba(0,0,0,0.07)
  static const Color colorNeutralShadowAmbientDarker = const Color(0x33000000); // rgba(0,0,0,0.20)
  static const Color colorNeutralShadowKeyDarker = const Color(0x3D000000); // rgba(0,0,0,0.24)
  static const Color colorBrandShadowAmbient = const Color(0x4D000000); // rgba(0,0,0,0.30)
  static const Color colorBrandShadowKey = const Color(0x40000000); // rgba(0,0,0,0.25)
}

/// Fluent 2 semantic colors — dark theme.
abstract class FluentDarkColors {
  static const Color colorNeutralForeground1 = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForeground1Hover = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForeground1Pressed = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForeground1Selected = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForeground2 = const Color(0xFFD6D6D6); // #d6d6d6
  static const Color colorNeutralForeground2Hover = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForeground2Pressed = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForeground2Selected = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForeground2BrandHover = const Color(0xFF479EF5); // #479ef5
  static const Color colorNeutralForeground2BrandPressed = const Color(0xFF2886DE); // #2886de
  static const Color colorNeutralForeground2BrandSelected = const Color(0xFF479EF5); // #479ef5
  static const Color colorNeutralForeground3 = const Color(0xFFADADAD); // #adadad
  static const Color colorNeutralForeground3Hover = const Color(0xFFD6D6D6); // #d6d6d6
  static const Color colorNeutralForeground3Pressed = const Color(0xFFD6D6D6); // #d6d6d6
  static const Color colorNeutralForeground3Selected = const Color(0xFFD6D6D6); // #d6d6d6
  static const Color colorNeutralForeground3BrandHover = const Color(0xFF479EF5); // #479ef5
  static const Color colorNeutralForeground3BrandPressed = const Color(0xFF2886DE); // #2886de
  static const Color colorNeutralForeground3BrandSelected = const Color(0xFF479EF5); // #479ef5
  static const Color colorNeutralForeground4 = const Color(0xFF999999); // #999999
  static const Color colorNeutralForeground5 = const Color(0xFFADADAD); // #adadad
  static const Color colorNeutralForeground5Hover = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForeground5Pressed = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForeground5Selected = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForegroundDisabled = const Color(0xFF5C5C5C); // #5c5c5c
  static const Color colorNeutralForegroundInvertedDisabled = const Color(0x66FFFFFF); // rgba(255, 255, 255, 0.4)
  static const Color colorBrandForegroundLink = const Color(0xFF479EF5); // #479ef5
  static const Color colorBrandForegroundLinkHover = const Color(0xFF62ABF5); // #62abf5
  static const Color colorBrandForegroundLinkPressed = const Color(0xFF2886DE); // #2886de
  static const Color colorBrandForegroundLinkSelected = const Color(0xFF479EF5); // #479ef5
  static const Color colorNeutralForeground2Link = const Color(0xFFD6D6D6); // #d6d6d6
  static const Color colorNeutralForeground2LinkHover = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForeground2LinkPressed = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForeground2LinkSelected = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorCompoundBrandForeground1 = const Color(0xFF479EF5); // #479ef5
  static const Color colorCompoundBrandForeground1Hover = const Color(0xFF62ABF5); // #62abf5
  static const Color colorCompoundBrandForeground1Pressed = const Color(0xFF2886DE); // #2886de
  static const Color colorBrandForeground1 = const Color(0xFF479EF5); // #479ef5
  static const Color colorBrandForeground2 = const Color(0xFF62ABF5); // #62abf5
  static const Color colorBrandForeground2Hover = const Color(0xFF96C6FA); // #96c6fa
  static const Color colorBrandForeground2Pressed = const Color(0xFFEBF3FC); // #ebf3fc
  static const Color colorNeutralForeground1Static = const Color(0xFF242424); // #242424
  static const Color colorNeutralForegroundStaticInverted = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForegroundInverted = const Color(0xFF242424); // #242424
  static const Color colorNeutralForegroundInvertedHover = const Color(0xFF242424); // #242424
  static const Color colorNeutralForegroundInvertedPressed = const Color(0xFF242424); // #242424
  static const Color colorNeutralForegroundInvertedSelected = const Color(0xFF242424); // #242424
  static const Color colorNeutralForegroundInverted2 = const Color(0xFF242424); // #242424
  static const Color colorNeutralForegroundOnBrand = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForegroundInvertedLink = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForegroundInvertedLinkHover = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForegroundInvertedLinkPressed = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralForegroundInvertedLinkSelected = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorBrandForegroundInverted = const Color(0xFF0F6CBD); // #0f6cbd
  static const Color colorBrandForegroundInvertedHover = const Color(0xFF115EA3); // #115ea3
  static const Color colorBrandForegroundInvertedPressed = const Color(0xFF0F548C); // #0f548c
  static const Color colorBrandForegroundOnLight = const Color(0xFF0F6CBD); // #0f6cbd
  static const Color colorBrandForegroundOnLightHover = const Color(0xFF115EA3); // #115ea3
  static const Color colorBrandForegroundOnLightPressed = const Color(0xFF0E4775); // #0e4775
  static const Color colorBrandForegroundOnLightSelected = const Color(0xFF0F548C); // #0f548c
  static const Color colorNeutralBackground1 = const Color(0xFF292929); // #292929
  static const Color colorNeutralBackground1Hover = const Color(0xFF3D3D3D); // #3d3d3d
  static const Color colorNeutralBackground1Pressed = const Color(0xFF1F1F1F); // #1f1f1f
  static const Color colorNeutralBackground1Selected = const Color(0xFF383838); // #383838
  static const Color colorNeutralBackground2 = const Color(0xFF1F1F1F); // #1f1f1f
  static const Color colorNeutralBackground2Hover = const Color(0xFF333333); // #333333
  static const Color colorNeutralBackground2Pressed = const Color(0xFF141414); // #141414
  static const Color colorNeutralBackground2Selected = const Color(0xFF2E2E2E); // #2e2e2e
  static const Color colorNeutralBackground3 = const Color(0xFF141414); // #141414
  static const Color colorNeutralBackground3Hover = const Color(0xFF292929); // #292929
  static const Color colorNeutralBackground3Pressed = const Color(0xFF0A0A0A); // #0a0a0a
  static const Color colorNeutralBackground3Selected = const Color(0xFF242424); // #242424
  static const Color colorNeutralBackground4 = const Color(0xFF0A0A0A); // #0a0a0a
  static const Color colorNeutralBackground4Hover = const Color(0xFF1F1F1F); // #1f1f1f
  static const Color colorNeutralBackground4Pressed = const Color(0xFF000000); // #000000
  static const Color colorNeutralBackground4Selected = const Color(0xFF1A1A1A); // #1a1a1a
  static const Color colorNeutralBackground5 = const Color(0xFF000000); // #000000
  static const Color colorNeutralBackground5Hover = const Color(0xFF141414); // #141414
  static const Color colorNeutralBackground5Pressed = const Color(0xFF050505); // #050505
  static const Color colorNeutralBackground5Selected = const Color(0xFF0F0F0F); // #0f0f0f
  static const Color colorNeutralBackground6 = const Color(0xFF333333); // #333333
  static const Color colorNeutralBackground7 = const Color(0x00000000); // #00000000
  static const Color colorNeutralBackground7Hover = const Color(0xFF1A1A1A); // #1a1a1a
  static const Color colorNeutralBackground7Pressed = const Color(0xFF0A0A0A); // #0a0a0a
  static const Color colorNeutralBackground7Selected = const Color(0x00000000); // #00000000
  static const Color colorNeutralBackground8 = const Color(0xFF292929); // #292929
  static const Color colorNeutralBackgroundInverted = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralBackgroundInvertedHover = const Color(0xFFF5F5F5); // #f5f5f5
  static const Color colorNeutralBackgroundInvertedPressed = const Color(0xFFE0E0E0); // #e0e0e0
  static const Color colorNeutralBackgroundInvertedSelected = const Color(0xFFEBEBEB); // #ebebeb
  static const Color colorNeutralBackgroundStatic = const Color(0xFF3D3D3D); // #3d3d3d
  static const Color colorNeutralBackgroundAlpha = const Color(0x801A1A1A); // rgba(26, 26, 26, 0.5)
  static const Color colorNeutralBackgroundAlpha2 = const Color(0xB31F1F1F); // rgba(31, 31, 31, 0.7)
  static const Color colorSubtleBackground = const Color(0x00000000); // transparent
  static const Color colorSubtleBackgroundHover = const Color(0xFF383838); // #383838
  static const Color colorSubtleBackgroundPressed = const Color(0xFF2E2E2E); // #2e2e2e
  static const Color colorSubtleBackgroundSelected = const Color(0xFF333333); // #333333
  static const Color colorSubtleBackgroundLightAlphaHover = const Color(0xCC242424); // rgba(36, 36, 36, 0.8)
  static const Color colorSubtleBackgroundLightAlphaPressed = const Color(0x80242424); // rgba(36, 36, 36, 0.5)
  static const Color colorSubtleBackgroundLightAlphaSelected = const Color(0x00000000); // transparent
  static const Color colorSubtleBackgroundInverted = const Color(0x00000000); // transparent
  static const Color colorSubtleBackgroundInvertedHover = const Color(0x1A000000); // rgba(0, 0, 0, 0.1)
  static const Color colorSubtleBackgroundInvertedPressed = const Color(0x4D000000); // rgba(0, 0, 0, 0.3)
  static const Color colorSubtleBackgroundInvertedSelected = const Color(0x33000000); // rgba(0, 0, 0, 0.2)
  static const Color colorTransparentBackground = const Color(0x00000000); // transparent
  static const Color colorTransparentBackgroundHover = const Color(0x00000000); // transparent
  static const Color colorTransparentBackgroundPressed = const Color(0x00000000); // transparent
  static const Color colorTransparentBackgroundSelected = const Color(0x00000000); // transparent
  static const Color colorNeutralBackgroundDisabled = const Color(0xFF141414); // #141414
  static const Color colorNeutralBackgroundDisabled2 = const Color(0xFF292929); // #292929
  static const Color colorNeutralBackgroundInvertedDisabled = const Color(0x1AFFFFFF); // rgba(255, 255, 255, 0.1)
  static const Color colorNeutralStencil1 = const Color(0xFF575757); // #575757
  static const Color colorNeutralStencil2 = const Color(0xFF333333); // #333333
  static const Color colorNeutralStencil1Alpha = const Color(0x1AFFFFFF); // rgba(255, 255, 255, 0.1)
  static const Color colorNeutralStencil2Alpha = const Color(0xDFFFFFF); // rgba(255, 255, 255, 0.05)
  static const Color colorBackgroundOverlay = const Color(0x80000000); // rgba(0, 0, 0, 0.5)
  static const Color colorScrollbarOverlay = const Color(0x99FFFFFF); // rgba(255, 255, 255, 0.6)
  static const Color colorBrandBackground = const Color(0xFF115EA3); // #115ea3
  static const Color colorBrandBackgroundHover = const Color(0xFF0F6CBD); // #0f6cbd
  static const Color colorBrandBackgroundPressed = const Color(0xFF0C3B5E); // #0c3b5e
  static const Color colorBrandBackgroundSelected = const Color(0xFF0F548C); // #0f548c
  static const Color colorCompoundBrandBackground = const Color(0xFF479EF5); // #479ef5
  static const Color colorCompoundBrandBackgroundHover = const Color(0xFF62ABF5); // #62abf5
  static const Color colorCompoundBrandBackgroundPressed = const Color(0xFF2886DE); // #2886de
  static const Color colorBrandBackgroundStatic = const Color(0xFF0F6CBD); // #0f6cbd
  static const Color colorBrandBackground2 = const Color(0xFF082338); // #082338
  static const Color colorBrandBackground2Hover = const Color(0xFF0C3B5E); // #0c3b5e
  static const Color colorBrandBackground2Pressed = const Color(0xFF061724); // #061724
  static const Color colorBrandBackground3Static = const Color(0xFF0F548C); // #0f548c
  static const Color colorBrandBackground4Static = const Color(0xFF0C3B5E); // #0c3b5e
  static const Color colorBrandBackgroundInverted = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorBrandBackgroundInvertedHover = const Color(0xFFEBF3FC); // #ebf3fc
  static const Color colorBrandBackgroundInvertedPressed = const Color(0xFFB4D6FA); // #b4d6fa
  static const Color colorBrandBackgroundInvertedSelected = const Color(0xFFCFE4FA); // #cfe4fa
  static const Color colorNeutralCardBackground = const Color(0xFF333333); // #333333
  static const Color colorNeutralCardBackgroundHover = const Color(0xFF3D3D3D); // #3d3d3d
  static const Color colorNeutralCardBackgroundPressed = const Color(0xFF2E2E2E); // #2e2e2e
  static const Color colorNeutralCardBackgroundSelected = const Color(0xFF383838); // #383838
  static const Color colorNeutralCardBackgroundDisabled = const Color(0xFF141414); // #141414
  static const Color colorNeutralStrokeAccessible = const Color(0xFFADADAD); // #adadad
  static const Color colorNeutralStrokeAccessibleHover = const Color(0xFFBDBDBD); // #bdbdbd
  static const Color colorNeutralStrokeAccessiblePressed = const Color(0xFFB3B3B3); // #b3b3b3
  static const Color colorNeutralStrokeAccessibleSelected = const Color(0xFF479EF5); // #479ef5
  static const Color colorNeutralStroke1 = const Color(0xFF666666); // #666666
  static const Color colorNeutralStroke1Hover = const Color(0xFF757575); // #757575
  static const Color colorNeutralStroke1Pressed = const Color(0xFF6B6B6B); // #6b6b6b
  static const Color colorNeutralStroke1Selected = const Color(0xFF707070); // #707070
  static const Color colorNeutralStroke2 = const Color(0xFF525252); // #525252
  static const Color colorNeutralStroke3 = const Color(0xFF3D3D3D); // #3d3d3d
  static const Color colorNeutralStroke4 = const Color(0xFF3D3D3D); // #3d3d3d
  static const Color colorNeutralStroke4Hover = const Color(0xFF2E2E2E); // #2e2e2e
  static const Color colorNeutralStroke4Pressed = const Color(0xFF242424); // #242424
  static const Color colorNeutralStroke4Selected = const Color(0xFF3D3D3D); // #3d3d3d
  static const Color colorNeutralStrokeSubtle = const Color(0xFF0A0A0A); // #0a0a0a
  static const Color colorNeutralStrokeOnBrand = const Color(0xFF292929); // #292929
  static const Color colorNeutralStrokeOnBrand2 = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralStrokeOnBrand2Hover = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralStrokeOnBrand2Pressed = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralStrokeOnBrand2Selected = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorBrandStroke1 = const Color(0xFF479EF5); // #479ef5
  static const Color colorBrandStroke2 = const Color(0xFF0E4775); // #0e4775
  static const Color colorBrandStroke2Hover = const Color(0xFF0E4775); // #0e4775
  static const Color colorBrandStroke2Pressed = const Color(0xFF0A2E4A); // #0a2e4a
  static const Color colorBrandStroke2Contrast = const Color(0xFF0E4775); // #0e4775
  static const Color colorCompoundBrandStroke = const Color(0xFF479EF5); // #479ef5
  static const Color colorCompoundBrandStrokeHover = const Color(0xFF62ABF5); // #62abf5
  static const Color colorCompoundBrandStrokePressed = const Color(0xFF2886DE); // #2886de
  static const Color colorNeutralStrokeDisabled = const Color(0xFF424242); // #424242
  static const Color colorNeutralStrokeDisabled2 = const Color(0xFF3D3D3D); // #3d3d3d
  static const Color colorNeutralStrokeInvertedDisabled = const Color(0x66FFFFFF); // rgba(255, 255, 255, 0.4)
  static const Color colorTransparentStroke = const Color(0x00000000); // transparent
  static const Color colorTransparentStrokeInteractive = const Color(0x00000000); // transparent
  static const Color colorTransparentStrokeDisabled = const Color(0x00000000); // transparent
  static const Color colorNeutralStrokeAlpha = const Color(0x1AFFFFFF); // rgba(255, 255, 255, 0.1)
  static const Color colorNeutralStrokeAlpha2 = const Color(0x33FFFFFF); // rgba(255, 255, 255, 0.2)
  static const Color colorStrokeFocus1 = const Color(0xFF000000); // #000000
  static const Color colorStrokeFocus2 = const Color(0xFFFFFFFF); // #ffffff
  static const Color colorNeutralShadowAmbient = const Color(0x3D000000); // rgba(0,0,0,0.24)
  static const Color colorNeutralShadowKey = const Color(0x47000000); // rgba(0,0,0,0.28)
  static const Color colorNeutralShadowAmbientLighter = const Color(0x1F000000); // rgba(0,0,0,0.12)
  static const Color colorNeutralShadowKeyLighter = const Color(0x24000000); // rgba(0,0,0,0.14)
  static const Color colorNeutralShadowAmbientDarker = const Color(0x66000000); // rgba(0,0,0,0.40)
  static const Color colorNeutralShadowKeyDarker = const Color(0x7A000000); // rgba(0,0,0,0.48)
  static const Color colorBrandShadowAmbient = const Color(0x4D000000); // rgba(0,0,0,0.30)
  static const Color colorBrandShadowKey = const Color(0x40000000); // rgba(0,0,0,0.25)
}

/// Fluent 2 global design tokens (spacing, radius, duration, typography).
abstract class FluentTokens {
  // ---- spacing (4px base scale) ----
  static const double spacingHorizontalNone = 0; // 0
  static const double spacingHorizontalXXS = 2; // 2px
  static const double spacingHorizontalXS = 4; // 4px
  static const double spacingHorizontalSNudge = 6; // 6px
  static const double spacingHorizontalS = 8; // 8px
  static const double spacingHorizontalMNudge = 10; // 10px
  static const double spacingHorizontalM = 12; // 12px
  static const double spacingHorizontalL = 16; // 16px
  static const double spacingHorizontalXL = 20; // 20px
  static const double spacingHorizontalXXL = 24; // 24px
  static const double spacingHorizontalXXXL = 32; // 32px

  // ---- border radius ----
  static const double borderRadiusNone = 0; // 0
  static const double borderRadiusSmall = 2; // 2px
  static const double borderRadiusMedium = 4; // 4px
  static const double borderRadiusLarge = 6; // 6px
  static const double borderRadiusXLarge = 8; // 8px
  static const double borderRadius2XLarge = 12; // 12px
  static const double borderRadius3XLarge = 16; // 16px
  static const double borderRadius4XLarge = 24; // 24px
  static const double borderRadius5XLarge = 32; // 32px
  static const double borderRadius6XLarge = 40; // 40px
  static const double borderRadiusCircular = 10000; // 10000px

  // ---- motion duration ----
  static const Duration durationUltraFast = Duration(milliseconds: 50); // 50ms
  static const Duration durationFaster = Duration(milliseconds: 100); // 100ms
  static const Duration durationFast = Duration(milliseconds: 150); // 150ms
  static const Duration durationNormal = Duration(milliseconds: 200); // 200ms
  static const Duration durationGentle = Duration(milliseconds: 250); // 250ms
  static const Duration durationSlow = Duration(milliseconds: 300); // 300ms
  static const Duration durationSlower = Duration(milliseconds: 400); // 400ms
  static const Duration durationUltraSlow = Duration(milliseconds: 500); // 500ms

  // ---- font sizes ----
  static const double fontSizeBase100 = 10; // 10px
  static const double fontSizeBase200 = 12; // 12px
  static const double fontSizeBase300 = 14; // 14px
  static const double fontSizeBase400 = 16; // 16px
  static const double fontSizeBase500 = 20; // 20px
  static const double fontSizeBase600 = 24; // 24px
  static const double fontSizeHero700 = 28; // 28px
  static const double fontSizeHero800 = 32; // 32px
  static const double fontSizeHero900 = 40; // 40px
  static const double fontSizeHero1000 = 68; // 68px

  // ---- font weights ----
  static const FontWeight fontWeightRegular = FontWeight.w400; // 400
  static const FontWeight fontWeightMedium = FontWeight.w500; // 500
  static const FontWeight fontWeightSemibold = FontWeight.w600; // 600
  static const FontWeight fontWeightBold = FontWeight.w700; // 700
}
